name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ] 
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ""
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Image Name to lowercase
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Setzt immer :latest, wenn du auf den main-Branch pushst
            type=raw,value=latest,enable={{is_default_branch}}
            # Extrahiert die Version aus deinem GitHub-Tag (z.B. aus v1.1.0 wird :1.1.0)
            type=semver,pattern={{version}}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Hier nutzt er jetzt die magischen Tags aus dem Meta-Schritt
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}